import "./globals.css";
import type { Metadata } from "next";
import { Sunflower } from "next/font/google";
import WrapperBg from "./components/layout/WrapperBg";
import Header from "./components/layout/Header";
import { Toaster } from "react-hot-toast";

const sunflower = Sunflower({
  subsets: ["latin"],
  weight: ["300", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sunflower.className}>
        <Toaster position="top-center" reverseOrder={false} />
        <WrapperBg>
          <Header />
          {children}
        </WrapperBg>
      </body>
    </html>
  );
}
